### PR TITLE
Update StringUtils.cpp

### PR DESCRIPTION
**Pull request by dcb314**
Faster and simpler implementation of chop.

### CODE REVIEW

**Comment by jxyang** [comment]
Thanks for the optimization. @dcb314

**Comment by FangLinglong** [comment]
@jxyang @dcb314 
This MR can cause compilation errors. The parameter name is str and the local variable is s. Please check.

**Comment by dcb314** [comment]
You don't share the compilation error with us, but I think if you have a parameter name of "str",
then that sounds wrong. Current version of chop - git willing - should be something like

void
StringUtils :: chop( string & s)
{  
   size_t p = s.find_first_not_of( " \t");
   s.erase( 0, p);
        
   p = s.find_last_not_of( " \t");
   if (string::npos != p)
   {
      s.erase(p + 1);
   }
}

**Comment by FangLinglong** [comment]
> You don't share the compilation error with us, but I think if you have a parameter name of "str", then that sounds wrong. Current version of chop - git willing - should be something like
> 
> void StringUtils :: chop( string & s) { size_t p = s.find_first_not_of( " \t"); s.erase( 0, p);
> 
> p = s.find_last_not_of( " \t"); if (string::npos != p) { s.erase(p + 1); } }

--------------
image

**Comment by dcb314** [comment]
Your analysis in red looks accurate. I have no idea how this
passed acceptance testing. User jxyang did the merge. 
Perhaps they can offer an opinion ?

**Pull request merged**
